### ISSUE TITLE
多个mqtt连接,在小程序中会丢失?

### ISSUE THREAD

**Issue by 849511441** [xuhongv/WeChat_Esp8266#1]
比如我想在小程序中多实例化几个 mqtt ，小程序中写道websocket 最多5个,我多实例化的那几个 我研究过是没有发送心跳就断开了只有一个在发送心跳，其实本应该可以多个的 ,想问问有没有办法适应多个 mqtt连接 看看有没有大神 修改源码等等 实现实现  多谢了

**Comment by xuhongv** [comment]
- mqtt.js 的使用文档你去看看，我也没用个多连接实例

**Comment by 849511441** [comment]
好吧

**Comment by xuhongv** [comment]
- 秒回啊兄弟

**Comment by 849511441** [comment]
当然啊，这是我的工作
