### ISSUE TITLE
微信小程序模拟器可以连接上，真机还是连接不上

### ISSUE THREAD

**Issue by lzcdev** [xuhongv/WeChat_Esp8266#2]
模拟器的日志
![11441559286194_ pic_hd](https://user-images.githubusercontent.com/16014249/58687935-a3af3a80-83b5-11e9-83b6-783ea4ee81e5.jpg)

真机调试的日志：
点了连接之后没反应，过一会就失败了，现象就是一直连不上
![11451559286354_ pic_hd](https://user-images.githubusercontent.com/16014249/58687985-bfb2dc00-83b5-11e9-892b-0b96670ccc56.jpg)

**Comment by xuhongv** [comment]
- 真机调试需要在微信公众号后台把mqtt服务器的域名设置为安全域名哦！
