### ISSUE TITLE
this is not good at mobile phone 手机上与服务器通讯有问题

### ISSUE THREAD

**Issue by isharrrry** [xuhongv/WeChat_Esp8266#3]
模拟器很稳定，但是在手机扫描预览后连接不上服务器。另外就是这个库开代码保护就不能编译。

![image](https://user-images.githubusercontent.com/25739168/59833467-af6c9c00-9378-11e9-9789-f033ad758d70.png)

**Comment by isharrrry** [comment]
两个服务器在模拟器都是跑通的，尝试过开关安全域名都一样，其中这个是阿里云服务器
![image](https://user-images.githubusercontent.com/25739168/59833760-55b8a180-9379-11e9-8b03-6af6596db93d.png)

**Comment by xuhongv** [comment]
- 检查合法域名？

**Comment by xuhongv** [comment]
- clinetID不能一样

**Comment by isharrrry** [comment]
> * clinetID不能一样

域名是合法的，我是两个小程序测试，clinetID一个是mqttjs提供的随机生成，一个是阿里云的测试clinetID

**Comment by xuhongv** [comment]
我上午试下，用真机调试和真机预览都可以成功连接。没有你的问题复现。

**Comment by isharrrry** [comment]
> 我上午试下，用真机调试和真机预览都可以成功连接。没有你的问题复现。

还有就是当连接断开时没法读client的属性判断，这个有办法解决吗

**Comment by xuhongv** [comment]
你去拉取下 mqtt.js 源码版本试下应该可以修复。

**Comment by xuhongv** [comment]
我刚刚从 npm 拉取了一版更新了，你拉取试下！
