### ISSUE TITLE
支付宝小程序链接mqtt报错

### ISSUE THREAD

**Issue by geeksfan** [xuhongv/WeChat_Esp8266#6]
真机调试报错
![image](https://user-images.githubusercontent.com/31240793/69496380-94481e80-0f0c-11ea-8ca1-f4e708954cd2.png)

模拟器报错
![image](https://user-images.githubusercontent.com/31240793/69496369-7ed2f480-0f0c-11ea-8c6d-dd0c73e33dc3.png)

预览报错
![image](https://user-images.githubusercontent.com/31240793/69496083-146c8500-0f09-11ea-9b45-03fc24533913.png)

希望予以解答，谢谢

**Comment by xuhongv** [comment]
必须真机调试
