### ISSUE TITLE
my.onSocketMessage((res) => {

### ISSUE THREAD

**Issue by geeksfan** [xuhongv/WeChat_Esp8266#7]
![image](https://user-images.githubusercontent.com/31240793/69522755-25ff6c80-0f9d-11ea-8819-8402be37a6c3.png)

![image](https://user-images.githubusercontent.com/31240793/69522789-416a7780-0f9d-11ea-8c72-59ab5eace611.png)

希望解答

**Comment by xuhongv** [comment]
连接出问题？什么问题
